### ISSUE TITLE
Validate email addresses

### ISSUE THREAD

**Issue by rajumsys** [SparkPost/ruby-sparkpost#11]
We need to validate recipient (`to`) and sender (`from`) email addresses in `Transmission` class.

**Comment by rajumsys** [comment]
Also `to` can be a recipient list id. So when a list ID is passed, it should not be validated for email.

**Comment by rajumsys** [comment]
One thing I didn't know until now is that recipient list ID can be string. So my plan (to consider it recipient list ID when `to` is numeric) can't be implemented. 

So, here is my revised thought. Let's not actually validate `to`. We give the responsibilities to the consumer (user of this library) and we do following:

If `to` is:
1) String and not an email address, we'll consider it as recipient list
2) Array, we'll assume it as email addresses. 

These are my concerns on the above plan:

1) Is there any use cases when `to` is an array of recipient list (multiple recipients list)? 
2) Does our platform support that? 
3) What will happen if `to` is an Array (which means we'll assume it as email address collection) and one (or some) email address is invalid? Will API reject the transmission or it'll work partially? 

Based on the following [quote from transmission api](https://www.sparkpost.com/api#/reference/transmissions), I assume answer to the question 1 & 2 is `NO`

> Specify a stored recipient list or specify recipients inline

Let me know your thoughts.

**Comment by rajumsys** [comment]
I've found the answer for 3rd question. API will work partially. It'll be partially successful. Here is a sample response. 

```
{"errors"=>[{"message"=>"transmission created, but with validation errors", "description"=>"message submitted for generation successfully", "code"=>"2000"}], "results"=>{"rcpt_to_errors"=>[{"message"=>"invalid data format/type", "description"=>"invalid recipient address.email: raju", "code"=>"1300"}], "total_rejected_recipients"=>1, "total_accepted_recipients"=>1, "id"=>"84233733603972755"}}
```

So it looks like we should validate email addresses before making the API call ONLY when it's a collection. We won't validate `to` when string. It sounds two different behavior but when `to` is string and invalid, there is no chance of partial success; it'll fail.

**Comment by AimeeKnight** [comment]
@rajumsys after talking through things with a few others who first developed the node library, I think we should just allow the api to surface the errors as you showed above. I definitely don't see an issue with that error message, it also prevents us from having to maintain unnecessary code, and keeps us consistent with the other libraries. Validating a recipient list and not a single recipient seems unintuitive from a maintainers standpoint, and couples our library pretty tightly with the API. Depending on the error surfaced, this could also cause confusion from a consumer standpoint if we surface errors that don't match the api exactly since it's hard to predict what kind of errors a user might see. Let me know what you think.

**Comment by rajumsys** [comment]
@AimeeKnight I appreciate your time to discuss and put your thoughts about it. 

Overall, I've a mixed feeling about it. I agree consistency with other libraries has some real values and also it feels little weird that we validate list but not single email address. However, the reasoning was because "we can't" when it's a single email. 

I personally like the idea of early exits. IMO, there is no point of passing through something that will obviously fail later and we know it now. Our library is to make users (not ours) life easier. So, we should probably think of alternative approach, like passing `list_id=true` or `skip_email_validation=true` (just saying) in options or something which tells us not to validate. 

However, as I've found on further investigation, it won't be great issue for now if we handle #14. So we can definitely defer this discussion for future and handle accordingly if this becomes an issue. 

(Y)
