### ISSUE TITLE
Handling partial success

### ISSUE THREAD

**Issue by rajumsys** [SparkPost/ruby-sparkpost#14]
I believe currently we're not correctly handling the partial success. If API call succeeds with warning, we'll still throw an delivery exception. 

So, may be, instead of returning plain hash, we should consider of returning some sort of object which contains num succeeded, num failed, any warning messages from API etc.

**Comment by rajumsys** [comment]
@AimeeKnight thoughts?

**Comment by AimeeKnight** [comment]
I don't think we should intercept any errors from the API. I think we should just pass the errors through to the library consumers as we do in the other libraries.

**Comment by rajumsys** [comment]
Thanks for your thought. 

So you think current behavior (to raise exception even though it partially failed) correct?

**Comment by AimeeKnight** [comment]
If the API call succeeds but with a warning, I think we should pass that through exactly as it it to the user. I have not looked at the node library in awhile, but it's my understanding that's how we implemented it there.

**Comment by richleland** [comment]
It is, we also do this for the other libraries as well.

**Comment by brian4d** [comment]
Is it possible to make this a priority issue? I just migrated from Mandrill and ran into this problem on the first multi-recipient message that we sent. The API returned error code 200 ("transmission created but with validation errors"). The gem raised an exception and did not return the "results", so my delayed_job retried several times before I caught it. Basically can't use the gem in production until this is fixed. Thanks.

**Comment by rajumsys** [comment]
@brian4d sorry to hear about your trouble and thanks for reporting. can you share your expectations here so that we can think around it? I mean, in such cases what the library should return? also we welcome PRs :).

**Comment by brian4d** [comment]
@rajumsys That was quick, thanks. My preference would be what @AimeeKnight suggested -- just pass the API response so I can use both "results" and "errors".

**Comment by brian4d** [comment]
@rajumsys That would also let me access response.status, wouldn't it? That way I can check for "200" to differentiate "success" (i.e. don't retry) from "failure" (i.e. retry).

**Comment by rajumsys** [comment]
@brian4d make sense. also we'll welcome if you can issue a PR with that change. 👍
