### ISSUE TITLE
Add support for stored templates

### ISSUE THREAD

**Issue by ewandennis** [SparkPost/ruby-sparkpost#16]

**Comment by rajumsys** [comment]
A few examples of how we want to use it will be helpful.

**Comment by ewandennis** [comment]
How about we interpret the `html` argument more generically as 'content'?  If its a string, the current behaviour survives so we keep backwards compatibility.

If its an hash, we treat it like a content object with one of the following structures
 - `{html: 'html part', text: 'text part'}`
 - `{email_rfc822: 'raw email body'}`
 - `{template_id: 'my-template-id'}`

So a stored template transmission might look like this:
```ruby
values = { substitution_data: { name: 'Sparky' } }
sp = SparkPost::Client.new
response = sp.transmission.send_message(
    'to@example.com',
    'from@example.com',
    'Subject line',
    { template_id: 'my-template-id' },
    { substitution_data: { fname: 'Sparky' } }
)
```

**Comment by thehungrycoder** [comment]
I think I really liked this idea. It will make much more sense than now (passing plain text in different argument). 

I'm not familiar with with `rfc822`. how we need to pass this to API?

**Comment by rajumsys** [comment]
So far it looks this change may not be backward compatible (if anyone uses keyword arguments). I'll make a PR soon and discuss there.

**Comment by daneelliotthamilton** [comment]
Is it that there is currently no support for accessing templates  stored on sparkpost?

**Comment by rajumsys** [comment]
@daneelliotthamilton are you trying to get the list of stored templates using API or use it in your transmission?

**Comment by daneelliotthamilton** [comment]
I am trying to use it in a transmission.

**Comment by rajumsys** [comment]
@daneelliotthamilton I just made some changes to our `send_payload` method in a [pending PR](https://github.com/SparkPost/ruby-sparkpost/pull/21) and you can use that to define stored template. Only downside is that you'll have to prepare the payload yourself. I've also put an example there how to use template id. Let me know thoughts.

**Comment by rajumsys** [comment]
We can now use template_id in transmission with `send_payload` method. I've put [an example in example directory](https://github.com/SparkPost/ruby-sparkpost/blob/master/examples/transmission/with_template.rb).

So closing this for now.

**Comment by daneelliotthamilton** [comment]
I think preparing the payload allows for greater flexibilty thanks

**Comment by rajumsys** [comment]
> I think preparing the payload allows for greater flexibilty thanks

:+1:
