### ISSUE TITLE
send_payload failing

### ISSUE THREAD

**Issue by bntzio** [SparkPost/ruby-sparkpost#23]
The method **send_payload()** is failing, when I run `welcome_message(user)` the console throws an error saying: *(Object doesn't support #inspect)*.

```
class UserMailer < ApplicationMailer
  require 'sparkpost'

  def welcome_message(user)
    @user = user
    payload = {
      recipients: [{ address: { email: @user.email } }],
      content: {
        template_id: 'phoenix-welcome-email'
      }
    }
    
    sparky = SparkPost::Client.new(ENV['SPARKPOST_API_KEY'])
    sparky.transmission.send_payload(payload)
  end
end
```

Any ideas why is this happening, possible fixes?

**Comment by rajumsys** [comment]
@bntzio Which line throwing that? Also if `payload` is your actual payload, it's missing other required data like `from`, `subject` etc.

**Comment by bntzio** [comment]
Even if I write `from`, `subject`, `to`, etc. It's failing, when I run `UserMailer.welcome_message(user)`, user being a user of my db, `user = User.first`, in my rails console, I get this:
```UserMailer#welcome_message: processed outbound mail in 1.7ms
(Object doesn't support #inspect)
=>```
And the email never arrives.

**Comment by rajumsys** [comment]
Can you please post the whole stack trace? I still don't understand exactly where it's coming from.

**Comment by bntzio** [comment]
That's everything I get.
```
irb(main):005:0* UserMailer.welcome_message(user)

UserMailer#welcome_message: processed outbound mail in 1.6ms
(Object doesn't support #inspect)
=>
```

**Comment by abrahamks** [comment]
Hi @rajumsys I also encountered the same error like @bntzio 

```
require 'sparkpost'
sp = SparkPost::Client.new(ENV['SPARKPOST_API_KEY'])

payload = {
  recipients: [{ address: { email: 'myemail@gmail.com' } }],
  content: {
    from: 'test@mydomain.com',
    subject: 'test email payload',
    template_id: 'test-templated-id'
  }
}

response = sp.transmission.send_payload(payload)
puts response
```

I made this code based on https://github.com/SparkPost/ruby-sparkpost/blob/master/examples/transmission/send.rb

Please advise. Thanks

**Comment by rajumsys** [comment]
@abrahamks I just tested your example at my end and I found it working. I used ruby `v2.2.1p85`. What the versions you are using. I can test against it.

**Comment by abrahamks** [comment]
@rajumsys 
I tested it by using `ruby 2.2.1p85` and `ruby 2.1.1p76` 

They returned the same error
```undefined method `send_payload' for #<SparkPost::Transmission:0x007fa81b260438> (NoMethodError)```

**Comment by rajumsys** [comment]
@abrahamks Thanks. That helps. 

This is actually a different problem that the OP reported. In your library, `send_payload` is not available. It may be you're using our gem version `0.1.2`. However, `send_payload` is ONLY available in our  `master` branch at this point. It's not released to a gem yet.

**Comment by abrahamks** [comment]
@rajumsys thanks, the error doesn't appear anymore.

**Comment by bntzio** [comment]
@rajumsys My ruby version is ruby 2.2.3p173
@rajumsys Did you create a method for the payload? or just the payload object inside your class?

Maybe that's what causing my error, I'm creating the payload and calling it in a method, and there's no methods in your examples.

**Comment by rajumsys** [comment]
> @rajumsys Did you create a method for the payload? or just the payload object inside your class?

I'm sorry, didn't get the question. 

The `send_payload` method is in transmission class which is merged to master recently. So, if you're still using gem, try pointing to our master branch. 

In your Gemfile, you can [directly mention git repo](http://bundler.io/v1.5/git.html)
```
gem 'sparkpost', :github => 'SparkPost/ruby-sparkpost'
```

**Comment by rajumsys** [comment]
@bntzio any update? Did it resolve the issue?

**Comment by bntzio** [comment]
@rajumsys Yep! It's working now! :smile:

Thank you!

**Comment by szymonbaranowski** [comment]
@rajumsys got the same error, mentioning github in my Gemfile did the job although it would be nice to release the master as the gem version so it's stays the same during multiple deployments. Right now any time you guys push something to the master branch it's gonna be included in my next deployment making my production and local environments out of sync.

**Comment by rajumsys** [comment]
@szymonbaranowski we're still working on a few things (mostly completion of template api, some change around this `send_payload`) before we cut a release. if you want to make it strict, probably pointing to a commit hash will be right thing to do for now which will prevent the issue you've mentioned. 

http://stackoverflow.com/questions/6119946/how-to-get-a-specific-commit-of-a-gem-from-github

**Comment by f0nk** [comment]
Hi @rajumsys , when will you be releasing a new version of the template API? I wish to be able to create new templates through the ruby gem but when I call the below I get the following error: "SparkPost::DeliveryException: [{"message"=>"Invalid domain", "description"=>"Unconfigured or unverified sending domain.", "code"=>"7001"}]"

I'm using gem 'sparkpost', :github => 'SparkPost/ruby-sparkpost' as the gem.

```
sp.template.create(
        'sample-template',
        nil,
        'test subject',
        '<h1>Hello Sparky</h1>',
        text: 'Hello Sparky',
        is_transactional: true,
        name: 'Sample Template',
        from_name: 'Sparky',
        from_email: 'me@me.com'
      )
 
```
