### ISSUE TITLE
Attachments don't work as expected

### ISSUE THREAD

**Issue by benross** [SparkPost/ruby-sparkpost#31]
The following is sending an email correctly, but there is nothing attached. Why not?

```
require 'sparkpost'
attachment = Base64.encode64('THIS IS A TOTALLY GENERIC AND PROFESSIONAL ATTACHMENT')
values = {
    attachments: [{
        name: 'attachment.txt',
        type: 'text/plain',
        data: attachment
    }]
}
sp = SparkPost::Client.new() 
sp.transmission.send_message('myemail@gmail.com', 'no-reply@mydomain.com', 'testemail', '<h1>Email with an attachment</h1>', values)
```

**Comment by rajumsys** [comment]
I just tested this I got the attachment in my email

https://www.dropbox.com/s/srsbkz2dy5c9zgz/Screenshot%202016-04-07%2015.31.02.png?dl=0

**Comment by benross** [comment]
Several of our devs have tried with different gmail addresses and no attachment is there. Thoughts how this can be resolved?

**Comment by rajumsys** [comment]
Is it possible to verify this using our other libraries? For example [python library](https://github.com/SparkPost/python-sparkpost). I want to nail down whether it's an issue with this library or your attachment sending abilities as whole. Also can you see if the raw email (`show original` in gmail). In my case, it's

```
Content-Type: text/plain
Content-Disposition: attachment; filename="attachment.txt"
Content-Transfer-Encoding: base64

VEhJUyBJUyBBIFRPVEFMTFkgR0VORVJJQyBBTkQgUFJPRkVTU0lPTkFMIEFU
VEFDSE1FTlQ=
```

**Comment by rajumsys** [comment]
Also can you post the payload, you can just put the `p data` in [this line](https://github.com/SparkPost/ruby-sparkpost/blob/master/lib/sparkpost/request.rb#L10). 

@yepher pointed out to this from our doc

> The content of the attachment as a Base64 encoded string. The string should not contain \r\n line breaks. The SparkPost systems will add line breaks as necessary to ensure the Base64 encoded lines contain no more than 76 characters each.

But we see that `encode64` has on `\n` the end. So I'll also suggest to try that.

**Comment by yepher** [comment]
@benross,

Can you try this?

```
require 'sparkpost'
attachment = Base64. strict_encode64('THIS IS A TOTALLY GENERIC AND PROFESSIONAL ATTACHMENT')
values = {
    attachments: [{
        name: 'attachment.txt',
        type: 'text/plain',
        data: attachment
    }]
}
sp = SparkPost::Client.new() 
sp.transmission.send_message('myemail@gmail.com', 'no-reply@mydomain.com', 'testemail', '<h1>Email with an attachment</h1>', values)
```

Basically change `Base64.encode64` to `Base64.strict_encode64 `

**Comment by willdembinski** [comment]
Hi there,

I'm currently working on this issue with Ben!

@yepher I just tried the strict_encode method.  To no avail.  This is my raw email:

`Delivered-To: willdembinski@gmail.com
Received: by 10.159.40.34 with SMTP id c31csp741903uac;
        Thu, 7 Apr 2016 14:32:14 -0700 (PDT)
X-Received: by 10.98.9.219 with SMTP id 88mr7806307pfj.0.1460064734774;
        Thu, 07 Apr 2016 14:32:14 -0700 (PDT)
Return-Path: <msprvs1=16905qdG771ID=bounces-25496@sparkpostmail.com>
Received: from outbound.sparkpostmail.com (outbound.sparkpostmail.com. [54.244.54.130])
        by mx.google.com with ESMTPS id g7si2124513pat.103.2016.04.07.14.32.14
        for <willdembinski@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 07 Apr 2016 14:32:14 -0700 (PDT)
Received-SPF: pass (google.com: domain of msprvs1=16905qdG771ID=bounces-25496@sparkpostmail.com designates 54.244.54.130 as permitted sender) client-ip=54.244.54.130;
Authentication-Results: mx.google.com;
       dkim=temperror (no key for signature) header.i=@powr.io;
       dkim=pass header.i=@sparkpostmail.com;
       spf=pass (google.com: domain of msprvs1=16905qdG771ID=bounces-25496@sparkpostmail.com designates 54.244.54.130 as permitted sender) smtp.mailfrom=msprvs1=16905qdG771ID=bounces-25496@sparkpostmail.com
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=powr.io; s=scph0316;
	t=1460064734; i=@powr.io;
	bh=pAF2IjUAC1KbxedJahf5qJceZHMjGyKt1vAKX19AdzI=;
	h=To:Date:Subject:From:List-Unsubscribe;
	b=Vrf3ZZy362HZBMGU5I4eexx7TL5fADqWPitgI2r//qT+RPen1zRv4zXslOU5qeP0T
	 EtRm9c5CtdqFi3uXg7TVnW/Kn8ReiIQVx4el6vVEMMR4d3L8CTaJvdPHmfSrr5ZHqv
	 TRTKjeeeTAwTaE21OrM/pdPAFe3cwbWdK/rTb3bw=
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=sparkpostmail.com;
	s=ssp1014; t=1460064734; i=@sparkpostmail.com;
	bh=pAF2IjUAC1KbxedJahf5qJceZHMjGyKt1vAKX19AdzI=;
	h=To:Date:Subject:From:List-Unsubscribe;
	b=r5/ntCUYFK3zkp50kO4FPgn68+uqNfruP+lH7A6teeuo6kcLmarYiYIDySbe+ot9H
	 Sqy0kIQ4gdGudJpqNZiMQI3CzJ6YZcrEYe9ukza7kOEzl83dcaP4U+wC6z+dneEJO9
	 JzOjcQA3JYpfqN5YMhbNYiXn3L+C7zw6+I5vKQaH/zYU+ZzqvExtmR3TaUwJcXo/Hv
	 l4n0YwtDkYUJ7XhRm30OXMEeW0LbjMeyfcDQwVTnwqF147safZVxiWBZumjEVL/LV5
	 Niuv1vzdl8Is36CQNujalt07VsHkz2D+qm3KqQRjkVA5lD31GocK6LpNtAKztq3o1I
	 vObT6tSsBuxIA==
X-MSFBL: QUZvZJtaYv8AemUZ1glpnEpcrxs/c5NSy5D/2jZknRY=|eyJtZXNzYWdlX2lkIjo
	iMDAwMWRlZDEwNjU3ZTYyOTIyZjMiLCJzdWJhY2NvdW50X2lkIjoiMCIsInJjcHR
	fbWV0YSI6e30sImIiOiJzdGFuZGFyZDMiLCJ0cmFuc21pc3Npb25faWQiOiIzMDI
	2MjE3MjYzNDczNDg4OCIsInIiOiJ3aWxsZGVtYmluc2tpQGdtYWlsLmNvbSIsImc
	iOiJiZ19zdGFuZGFyZCIsInRlbXBsYXRlX2lkIjoidGVtcGxhdGVfMzAyNjIxNzI
	2MzQ3MzQ4ODgiLCJ0ZW1wbGF0ZV92ZXJzaW9uIjoiMCIsImN1c3RvbWVyX2lkIjo
	iMjU0OTYiLCJmcmllbmRseV9mcm9tIjoibm8tcmVwbHlAcG93ci5pbyIsInJjcHR
	fdGFncyI6WyBdfQ==
Content-Transfer-Encoding: 7bit
Content-Type: text/html; charset="UTF-8"
To: willdembinski@gmail.com
Message-ID: <22.3F.10726.ED1D6075@momentum3.platform1.us-west-2.aws.cl.messagesystems.com>
Date: Thu, 07 Apr 2016 21:32:14 +0000
MIME-Version: 1.0
Subject: testemail
From: no-reply@powr.io
List-Unsubscribe: <mailto:unsubscribe@unsub.sparkpost.com?subject=unsubscribe:qAhCMLOIqXqWUdTNc018eVa3FtldaKyq0NcOHLoEkF4~|eyAicmNwdF90byI6ICJ3aWxsZGVtYmluc2tpQGdtYWlsLmNvbSIsICJyY3B0X21ldGEiOiAie30iLCAicmNwdF90YWdzIjogIlsgXSIsICJmcmllbmRseV9mcm9tIjogIm5vLXJlcGx5QHBvd3IuaW8iLCAidGVtcGxhdGVfaWQiOiAidGVtcGxhdGVfMzAyNjIxNzI2MzQ3MzQ4ODgiLCAidHJhbnNtaXNzaW9uX2lkIjogIjMwMjYyMTcyNjM0NzM0ODg4IiwgInRlbXBsYXRlX3ZlcnNpb24iOiAiMCIsICJjdXN0b21lcl9pZCI6ICIyNTQ5NiIsICJtYWlsZnJvbSI6ICJtc3BydnMxPTE2OTA1cWRHNzcxSUQ9Ym91bmNlcy0yNTQ5NkBzcGFya3Bvc3RtYWlsLmNvbSIsICJtZXNzYWdlX2lkIjogIjAwMDFkZWQxMDY1N2U2MjkyMmYzIiwgInN1YmFjY291bnRfaWQiOiAiMCIgfQ~~>

<h1>Email with an attachment</h1>
<img border="0" width="1" height="1" src="http://go.sparkpostmail.com/q/CvE3MDXERZn8NHGK9tW-IQ~~/AABjmAA~/RgRY6VbePkEIAGuDSSIGYSgXWAQAAAAAQgoAAd7RBlfmKSLzUhd3aWxsZGVtYmluc2tpQGdtYWlsLmNvbQlRBAAAAABHAnt9">`

**Comment by willdembinski** [comment]
@rajumsys Here is a raw message withOUT the strict_encoding addition:

```
                                                                                                                                                                                                                                                               
Delivered-To: willdembinski@gmail.com
Received: by 10.159.40.34 with SMTP id c31csp743299uac;
        Thu, 7 Apr 2016 14:36:29 -0700 (PDT)
X-Received: by 10.66.231.73 with SMTP id te9mr7746050pac.62.1460064988992;
        Thu, 07 Apr 2016 14:36:28 -0700 (PDT)
Return-Path: <msprvs1=16905qdG771ID=bounces-25496@sparkpostmail.com>
Received: from mta177a.sparkpostmail.com (mta177a.sparkpostmail.com. [52.38.191.227])
        by mx.google.com with ESMTPS id g23si2079499pfg.6.2016.04.07.14.36.28
        for <willdembinski@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 07 Apr 2016 14:36:28 -0700 (PDT)
Received-SPF: pass (google.com: domain of msprvs1=16905qdG771ID=bounces-25496@sparkpostmail.com designates 52.38.191.227 as permitted sender) client-ip=52.38.191.227;
Authentication-Results: mx.google.com;
       dkim=temperror (no key for signature) header.i=@powr.io;
       dkim=pass header.i=@sparkpostmail.com;
       spf=pass (google.com: domain of msprvs1=16905qdG771ID=bounces-25496@sparkpostmail.com designates 52.38.191.227 as permitted sender) smtp.mailfrom=msprvs1=16905qdG771ID=bounces-25496@sparkpostmail.com
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=powr.io; s=scph0316;
	t=1460064988; i=@powr.io;
	bh=VOna33GgMYVxH0+CfXgE55s+KbgfRN9PcLQFwWdhpus=;
	h=To:Date:Subject:From:List-Unsubscribe;
	b=FocecFwPVgIDG3GKu3bulI42RcKGoXox0RqaTh4mJMkedrhykaAZQ+a/mhj/GDsLm
	 tYr3dj6bolphUgz8PzcdaK1rUna+D4u/0txHP2+7mGViPC6vJVgSxsdq/cDm0B+Hgk
	 4KE3sfOo7ruCP1QW8iUcTTDwyr3UiwkIpnHcCwpY=
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=sparkpostmail.com;
	s=ssp1014; t=1460064988; i=@sparkpostmail.com;
	bh=VOna33GgMYVxH0+CfXgE55s+KbgfRN9PcLQFwWdhpus=;
	h=To:Date:Subject:From:List-Unsubscribe;
	b=WkBEzvxuaY5lEbi0eHEv4AM+ImP69DocmOuu/Va/jgEF3crKnXeih0ZjUpph97pmO
	 4xXA+hGfZ5b2r2SR4CUPNpOY0u9UnsWom5GLzzfG27UCzOFq6JAHkN/+A7TEVdpfHP
	 MX0cUUoV6ZtYiaPAkXUZMpXYju2kx1k9TInHi2/w99tu60Y/KnaNzh0xxXQ6kYGGbl
	 v6DOvrwGTr1/YrYRvzvcmfNtzuWWo6yFMNqwOjsVLL/J/zOHOF4fz8Oomzyl1H7TcF
	 84NlFMjm2vHGxMKLSRpeFgkJCSFqOwwIU4+m3x8oaAuqd27UZUJ1brPs+KNAeh6ylk
	 IOEXyKb7CQtrA==
X-MSFBL: Yloq8eIJ4vFH49eScT+Y79cJQxC5qDJ6UK6safmNcSg=|eyJzdWJhY2NvdW50X2l
	kIjoiMCIsInRyYW5zbWlzc2lvbl9pZCI6IjY2MjkwOTY3OTA4ODg3NTY3IiwiYiI
	6InN0YW5kYXJkNyIsIm1lc3NhZ2VfaWQiOiIwMDAzZGNkMjA2NTdjMDM0ODZmNiI
	sInJjcHRfdGFncyI6WyBdLCJjdXN0b21lcl9pZCI6IjI1NDk2IiwidGVtcGxhdGV
	faWQiOiJ0ZW1wbGF0ZV82NjI5MDk2NzkwODg4NzU2NyIsInRlbXBsYXRlX3ZlcnN
	pb24iOiIwIiwiZyI6ImJnX3N0YW5kYXJkIiwiciI6IndpbGxkZW1iaW5za2lAZ21
	haWwuY29tIiwicmNwdF9tZXRhIjp7fSwiZnJpZW5kbHlfZnJvbSI6Im5vLXJlcGx
	5QHBvd3IuaW8ifQ==
Content-Transfer-Encoding: 7bit
Content-Type: text/html; charset="UTF-8"
To: willdembinski@gmail.com
Message-ID: <68.6F.13504.CD2D6075@momentum1.platform1.us-west-2.aws.cl.messagesystems.com>
Date: Thu, 07 Apr 2016 21:36:28 +0000
MIME-Version: 1.0
Subject: testemail
From: no-reply@powr.io
List-Unsubscribe: <mailto:unsubscribe@unsub.sparkpost.com?subject=unsubscribe:2uKu6S8y2D2NgHB2dnoOPjCNbqda_Z7TEz_S7vYQoWI~|eyAicmNwdF90byI6ICJ3aWxsZGVtYmluc2tpQGdtYWlsLmNvbSIsICJyY3B0X21ldGEiOiAie30iLCAicmNwdF90YWdzIjogIlsgXSIsICJmcmllbmRseV9mcm9tIjogIm5vLXJlcGx5QHBvd3IuaW8iLCAidGVtcGxhdGVfaWQiOiAidGVtcGxhdGVfNjYyOTA5Njc5MDg4ODc1NjciLCAic3ViYWNjb3VudF9pZCI6ICIwIiwgInRlbXBsYXRlX3ZlcnNpb24iOiAiMCIsICJjdXN0b21lcl9pZCI6ICIyNTQ5NiIsICJtYWlsZnJvbSI6ICJtc3BydnMxPTE2OTA1cWRHNzcxSUQ9Ym91bmNlcy0yNTQ5NkBzcGFya3Bvc3RtYWlsLmNvbSIsICJtZXNzYWdlX2lkIjogIjAwMDNkY2QyMDY1N2MwMzQ4NmY2IiwgInRyYW5zbWlzc2lvbl9pZCI6ICI2NjI5MDk2NzkwODg4NzU2NyIgfQ~~>

<h1>Email with an attachment</h1>
<img border="0" width="1" height="1" src="http://go.sparkpostmail.com/q/VX4a92FXr5_hxwLHY_M2ew~~/AABjmAA~/RgRY6VfcPkEIAOuDSLoGrA8XWAQAAAAAQgoAA9zSBlfANIb2Uhd3aWxsZGVtYmluc2tpQGdtYWlsLmNvbQlRBAAAAABHAnt9">
```

**Comment by yepher** [comment]
Thanks for the RFC822 content. Can you also share the JSON that was generated?

you can just put the p data in this [line](https://github.com/SparkPost/ruby-sparkpost/blob/master/lib/sparkpost/request.rb#L10).

**Comment by willdembinski** [comment]
@yepher I'm sorry - I'm a slow person.  What json are you referring to?

**Comment by willdembinski** [comment]
This is the hash that is passed to the request method in SparkPost::Request

```
{:attachments=>[{:name=>"attachment.txt", :type=>"text/plain", :data=>"VEhJUyBJUyBBIFRPVEFMTFkgR0VORVJJQyBBTkQgUFJPRkVTU0lPTkFMIEFUVEFDSE1FTlQ="}], :recipients=>[{:address=>{:email=>"willdembinski@gmail.com"}}], :content=>{:from=>"no-reply@powr.io", :subject=>"testemail", :text=>nil, :html=>"<h1>Email with an attachment</h1>"}, :options=>{}}
```

**Comment by willdembinski** [comment]
The JSON
```
{"attachments":[{"name":"attachment.txt","type":"text/plain","data":"VEhJUyBJUyBBIFRPVEFMTFkgR0VORVJJQyBBTkQgUFJPRkVTU0lPTkFMIEFUVEFDSE1FTlQ="}],"recipients":[{"address":{"email":"willdembinski@gmail.com"}}],"content":{"from":"no-reply@powr.io","subject":"testemail","text":null,"html":"\u003ch1\u003eEmail with an attachment\u003c/h1\u003e"},"options":{}}
```

**Comment by willdembinski** [comment]
I dont think this is helpful but, this is the response from a message:

```
{"total_rejected_recipients"=>0, "total_accepted_recipients"=>1, "id"=>"102319768425953266"}
```

**Comment by willdembinski** [comment]
Also - this is the URI I think you might have been referring to:

```
https://api.sparkpost.com/api/v1/transmissions
```

**Comment by willdembinski** [comment]
Not trying to spam - however I couldnt help but notice that whichever version you referred me to had a distinctly different module than the one we are working with.  This is ours:

```
require 'net/http'
require 'json'

require_relative 'version'
require_relative 'exceptions'

module SparkPost
  module Request

    def request(url, api_key, data)
      uri = URI.parse(url)
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true
      headers = {
          'User-Agent' => 'ruby-sparkpost/' + VERSION,
          'Content-Type' => 'application/json',
          'Authorization' => api_key
      }
      req = Net::HTTP::Post.new(uri.path, initheader=headers)
      req.body = data.to_json

      process_response(http.request(req));
    end

    def process_response(response)
      response = JSON.parse(response.body)
      if response['errors']
        fail SparkPost::DeliveryException, response['errors']
      else
        response['results']
      end
    end    

    module_function :request, :process_response
  end
end
```

I also tried the module you linked me to - no success

**Comment by willdembinski** [comment]
Okidoki.  so when I cloned the current version of master.  It started working. Attachments deliver as intended.

This is problematic for people who - like us - rely on hosting platforms to handle certain aspects of dependencies.  (ie Heroku)

This makes me a sad panda

**Comment by yepher** [comment]
Great, so things are working now?

**Comment by willdembinski** [comment]
yes! thank you for your time and help!
