### ISSUE TITLE
How to send recipient specific substitutions?

### ISSUE THREAD

**Issue by benross** [SparkPost/ruby-sparkpost#32]
Documentation lacking in several basic areas:

- How to send to multiple addresses (i.e. not clear that you can have an array as the "to" field)
- How to specify a from name (i.e. not clear that the "from" can be a hash)
- How to specify substitutions on a per-recipient basis when there are multiple recipients (still don't understand how to do this).

**Comment by rajumsys** [comment]
@benross thanks for reporting. Yes, I agree the documentation is still lacking. We're not in v1.0.0 yet. So things are changing pretty quick. I hope it'll be much better over time. Also we'll appreciate if you submit PRs with doc/example update.

**Comment by yepher** [comment]
@benross,

I am not sure what you mean by `not clear that the "from" can be a hash`. Your from address should be a verified from domain.

**Comment by rajumsys** [comment]
> I am not sure what you mean by not clear that the "from" can be a hash. Your from address should be a verified from domain.

I believe, he meant the `from` arg in the `send_message` method which can optionally be a hash (with from name, email).

**Comment by damianmarti** [comment]
I think that there is not option to add substitutions per recipient. 
I made a change on the prepare_recipient https://github.com/damianmarti/ruby-sparkpost/commit/c0e044e3116a123330181f7ceec2c3162837ed2a to allow substutions per recipient. I didn't fixed or changed the broken tests.
I think that this library should be better designed. I found https://github.com/leadmachineapp/simple_spark simple and better.

**Comment by willdembinski** [comment]
For any interested parties.  This will generate 2 emails and deliver to test@gmail.com.

The first message will contain an address.name of "Bernie Sanders".

The second message will contain an address.name of "Margaret Thatcher".

```
  def send_mail()
    require 'sparkpost'
    from = {name:'Cool Guy', email:'support@somewhere.io'}
    params = {subject: "Test Email"}

    person1 = JSON.parse '{ "return_path": "123@bounces.domain.com", "address": { "email": "test@gmail.com", "name": "Bernie Sanders" }, "tags": [ "greeting", "prehistoric", "fred", "flintstone" ], "metadata": { "place": "Bedrock" }, "substitution_data": { "customer_type": "Platinum" } }'
    person2 = JSON.parse '{ "return_path": "123@bounces.domain.com", "address": { "email": "test@gmail.com", "name": "Margaret Thatcher" }, "tags": [ "greeting", "prehistoric", "fred", "flintstone" ], "metadata": { "place": "Bedrock" }, "substitution_data": { "customer_type": "Platinum" } }'
    bar = {recipients: [person1,person2]}

    message ="<p>Hello {{address.name}}!</p>"

    response = SparkPost::Client.new().transmission.send_message(["test@gmail.com","test@gmail.com"], from, params[:subject], message, bar)
  end
```

**Comment by willdembinski** [comment]
@damianmarti If you inspect https://github.com/SparkPost/ruby-sparkpost/blob/master/lib/sparkpost/request.rb you will see that the data is being attached the request object in the matter that this blog post:https://www.sparkpost.com/blog/advanced-email-templates/#.VwvKv3VhlhE outlines.

**Comment by richleland** [comment]
Due to incredible support and contributions from the community, we discontinued support of the official SparkPost ruby client library as of May 17, 2016. If you’re looking for an alternative, take a look at some of [these repositories](https://github.com/search?l=Ruby&q=sparkpost&type=Repositories&utf8=%E2%9C%93).
