### ISSUE TITLE
Build better sparkpost API wrapper for ruby

### ISSUE THREAD

**Issue by dmitry** [SparkPost/ruby-sparkpost#42]
First I tried this gem and then I found https://github.com/leadmachineapp/simple_spark and it looks more advanced and more ruby-idiomatic. I suggest you guys to join forces and build one, but better sparkpost API wrapper.

**Comment by benjaminwood** [comment]
👍 

The official wrapper here is very limited.

**Comment by darrencauthon** [comment]
Maybe make a new major release and make the flip?  I agree, the simple spark seems to be more idiomatic.

**Comment by jakcharlton** [comment]
Thanks for the plug @dmitry ... I guess I would agree ... one of the core strengths of Ruby is its dynamic nature, when dealing with APIs I tend to find trying to create strongly typed models and strong method signatures results in quite a lot of friction, hence why I wrote the simple_spark gem

Nothing inherently wrong with the official one, it was too limited for our app to use, but YMMV depending on your code style/preferences

**Comment by dmitry** [comment]
@jakcharlton from my point of view `simple_spark` just better because it's well documented, has more supported end-points and it's just more idiomatic to ruby. 

I believe it's possible to "merge" a code somehow and just work on the one codebase, instead of two.

@rajumsys any comments? :)

**Comment by jakcharlton** [comment]
I doubt very much they can be merged, they take totally different
approaches - one relies on strong method signatures, the other works on
hashes

Method signatures works just fine in a language that allows method
overloading, but rapidly becomes chaotic in Ruby. Keyword arguments in Ruby
would mean a dependency on Ruby 2, and fundamentally would only mean
reconstructing a hash from the arguments anyway.

I'm not adverse to any progress on either library, but I don't see much
natural synergy between the two

**Comment by jakcharlton** [comment]
One thing that might benefit the official gem would be to stop using Http
directly, and to move to using Excon or Typhoeus, they give much better
control of requests/responses and much better debug output

**Comment by jakcharlton** [comment]
I might also suggest providing a link to simple_spark from this gem, as they aren't in competition, and some people who find this one complex/unidiomatic may prefer the other, thoughts @rajumsys ?

**Comment by rajumsys** [comment]
> I might also suggest providing a link to simple_spark from this gem, as they aren't in competition, and some people who find this one complex/unidiomatic may prefer the other, thoughts @rajumsys ?

As we happily announce community efforts, I'm totally fine linking it in our repo. It's just a PR away ;).

**Comment by richleland** [comment]
Due to incredible support and contributions from the community, we discontinued support of the official SparkPost ruby client library as of May 17, 2016. If you’re looking for an alternative, take a look at some of [these repositories](https://github.com/search?l=Ruby&q=sparkpost&type=Repositories&utf8=%E2%9C%93).
